conformance:
  base-url: https://dev-conformance-passkey.daplatform.kr
logging:
  file:
    name: "./log/conformance.log"
  logback:
    rollingpolicy:
      file-name-pattern: "./log/conformance.%d{yyyy-MM-dd}.%i.log.gz"
      max-file-size: "10MB"
spring:
  thymeleaf:
    cache: true
  security:
    oauth2:
      client:
        registration:
          passkey-rp-scope:
            provider: sktelecom # authorization server (provider)'s identifier (see below)
            authorization-grant-type: client_credentials
            scope: passkey:rp
        provider:
          sktelecom:
            token-uri: https://dev-noti.daplatform.kr/oauth2/token
webauthn:
  rp:
    id: dev-conformance-passkey.daplatform.kr
  server:
    oauth2-protected: true